---
- name: Install maven
  hosts: localhost
  become: true
  tasks:
  - shell: apt-get upgrade -y; apt-get update
  - name: Install maven
    apt:
      name: maven
      state: latest
  - name: Install npm
    apt:
      name: npm
      state: latest
  - name: Install docker
    apt:
      name: docker
      state: latest
  - name: Install docker-compose
    apt:
      name: docker-compose
      state: latest
  - name: Install python3-pip
    apt:
      name: python3-pip
      state: latest
